UI:
  CtrlCSigint: false # for debug
  ExplosionKey: null #crash with stack traces (debug)

Quit:
  quitKey: "ctrl w"
  welcomeText: "Press *ctrl left* to edit!"

Sidebar:
  next: "ctrl right"
  prev: "ctrl left"

Highlight:
  Scheme:
    Concurrency: '10'
    Debug: '12'
    Delta: '2'
    Delta+: '3'
    Funge Space: '11'
    I/O: '214'
    Logic: '4'
    Math: '6'
    Nothing: '8'
    Position: '5'
    Repetition: '15'
    Stack: '159'
    Strings: '13'
    Termination: '1'
    Value: '7'

  Toggle: "ctrl h"
  DefaultEnable: true
  FlashingQuestionMark: false # non-ascii characters will also have a question mark

Paths:
  Toggle: "ctrl p"

Cursor:
  Up: "up"
  Down: "down"
  Left: "left"
  Right: "right"
  Step: "\n"

FungeScreen:
  OriginMarker: true

Run:
  StepKey: "ctrl r"
  RunKey: "ctrl x"